name: gh-pages
on:
  push:
    branches:
      - DRM-7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm build
  test-lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: npm test
      - run: npm lint
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test-lint]
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
