name: gh-pages
on:
  push:
    branches:
      - DRM-7

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm build
      - run: npm test
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    uses: crazy-max/ghaction-github-pages@v1
    with:
      target_branch: gh-pages
      build_dir: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
